{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "2fd465ee-5dda-4a34-935a-2e9161ed9ed7",
   "metadata": {},
   "outputs": [],
   "source": [
    "from kafka import KafkaConsumer, KafkaProducer\n",
    "from time import sleep\n",
    "from json import dumps,loads\n",
    "import json\n",
    "import s3fs\n",
    "from s3fs import S3FileSystem"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "96bc8c7a-0ce9-4b05-a4df-20dab7f8b96d",
   "metadata": {},
   "outputs": [],
   "source": [
    "consumer = KafkaConsumer('demotest',bootstrap_servers=['18.116.26.230:9092'], value_deserializer=lambda x:loads(x.decode('utf-8')))\n",
    "# for c in consumer:\n",
    "#     print(c.value)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "30025f9a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# import boto3\n",
    "\n",
    "# s3 = boto3.client('s3', region_name='us-east-2')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "33a9c319",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "abc85943-c580-4bdf-8be4-d3d5ef1142ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "s3 = S3FileSystem()\n",
    "s3 = s3fs.S3FileSystem(client_kwargs={'region_name': 'us-east-2'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "a221907d",
   "metadata": {},
   "outputs": [
    {
     "ename": "EndpointConnectionError",
     "evalue": "Could not connect to the endpoint URL: \"https://kafka-smp-bucket.s3.Ohious-east-2.amazonaws.com/stock_market_0.json\"",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mgaierror\u001b[39m                                  Traceback (most recent call last)",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiohttp/connector.py:1351\u001b[39m, in \u001b[36mTCPConnector._create_direct_connection\u001b[39m\u001b[34m(self, req, traces, timeout, client_error)\u001b[39m\n\u001b[32m   1347\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m   1348\u001b[39m     \u001b[38;5;66;03m# Cancelling this lookup should not cancel the underlying lookup\u001b[39;00m\n\u001b[32m   1349\u001b[39m     \u001b[38;5;66;03m#  or else the cancel event will get broadcast to all the waiters\u001b[39;00m\n\u001b[32m   1350\u001b[39m     \u001b[38;5;66;03m#  across all connections.\u001b[39;00m\n\u001b[32m-> \u001b[39m\u001b[32m1351\u001b[39m     hosts = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._resolve_host(host, port, traces=traces)\n\u001b[32m   1352\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mOSError\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiohttp/connector.py:995\u001b[39m, in \u001b[36mTCPConnector._resolve_host\u001b[39m\u001b[34m(self, host, port, traces)\u001b[39m\n\u001b[32m    994\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m995\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m asyncio.shield(resolved_host_task)\n\u001b[32m    996\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m asyncio.CancelledError:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiohttp/connector.py:1026\u001b[39m, in \u001b[36mTCPConnector._resolve_host_with_throttle\u001b[39m\u001b[34m(self, key, host, port, futures, traces)\u001b[39m\n\u001b[32m   1024\u001b[39m         \u001b[38;5;28;01mawait\u001b[39;00m trace.send_dns_resolvehost_start(host)\n\u001b[32m-> \u001b[39m\u001b[32m1026\u001b[39m addrs = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._resolver.resolve(host, port, family=\u001b[38;5;28mself\u001b[39m._family)\n\u001b[32m   1027\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m traces:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiohttp/resolver.py:39\u001b[39m, in \u001b[36mThreadedResolver.resolve\u001b[39m\u001b[34m(self, host, port, family)\u001b[39m\n\u001b[32m     36\u001b[39m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mresolve\u001b[39m(\n\u001b[32m     37\u001b[39m     \u001b[38;5;28mself\u001b[39m, host: \u001b[38;5;28mstr\u001b[39m, port: \u001b[38;5;28mint\u001b[39m = \u001b[32m0\u001b[39m, family: socket.AddressFamily = socket.AF_INET\n\u001b[32m     38\u001b[39m ) -> List[ResolveResult]:\n\u001b[32m---> \u001b[39m\u001b[32m39\u001b[39m     infos = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._loop.getaddrinfo(\n\u001b[32m     40\u001b[39m         host,\n\u001b[32m     41\u001b[39m         port,\n\u001b[32m     42\u001b[39m         \u001b[38;5;28mtype\u001b[39m=socket.SOCK_STREAM,\n\u001b[32m     43\u001b[39m         family=family,\n\u001b[32m     44\u001b[39m         flags=_AI_ADDRCONFIG,\n\u001b[32m     45\u001b[39m     )\n\u001b[32m     47\u001b[39m     hosts: List[ResolveResult] = []\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py:939\u001b[39m, in \u001b[36mBaseEventLoop.getaddrinfo\u001b[39m\u001b[34m(self, host, port, family, type, proto, flags)\u001b[39m\n\u001b[32m    937\u001b[39m     getaddr_func = socket.getaddrinfo\n\u001b[32m--> \u001b[39m\u001b[32m939\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m.run_in_executor(\n\u001b[32m    940\u001b[39m     \u001b[38;5;28;01mNone\u001b[39;00m, getaddr_func, host, port, family, \u001b[38;5;28mtype\u001b[39m, proto, flags)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/thread.py:59\u001b[39m, in \u001b[36m_WorkItem.run\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m     58\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m---> \u001b[39m\u001b[32m59\u001b[39m     result = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     60\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socket.py:977\u001b[39m, in \u001b[36mgetaddrinfo\u001b[39m\u001b[34m(host, port, family, type, proto, flags)\u001b[39m\n\u001b[32m    976\u001b[39m addrlist = []\n\u001b[32m--> \u001b[39m\u001b[32m977\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m res \u001b[38;5;129;01min\u001b[39;00m \u001b[43m_socket\u001b[49m\u001b[43m.\u001b[49m\u001b[43mgetaddrinfo\u001b[49m\u001b[43m(\u001b[49m\u001b[43mhost\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mport\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfamily\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mtype\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mproto\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mflags\u001b[49m\u001b[43m)\u001b[49m:\n\u001b[32m    978\u001b[39m     af, socktype, proto, canonname, sa = res\n",
      "\u001b[31mgaierror\u001b[39m: [Errno 8] nodename nor servname provided, or not known",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[31mClientConnectorDNSError\u001b[39m                   Traceback (most recent call last)",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/httpsession.py:222\u001b[39m, in \u001b[36mAIOHTTPSession.send\u001b[39m\u001b[34m(self, request)\u001b[39m\n\u001b[32m    221\u001b[39m session = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._get_session(proxy_url)\n\u001b[32m--> \u001b[39m\u001b[32m222\u001b[39m response = \u001b[38;5;28;01mawait\u001b[39;00m session.request(\n\u001b[32m    223\u001b[39m     request.method,\n\u001b[32m    224\u001b[39m     url=url,\n\u001b[32m    225\u001b[39m     chunked=\u001b[38;5;28mself\u001b[39m._chunked(headers_),\n\u001b[32m    226\u001b[39m     headers=headers_,\n\u001b[32m    227\u001b[39m     data=data,\n\u001b[32m    228\u001b[39m     proxy=proxy_url,\n\u001b[32m    229\u001b[39m     proxy_headers=proxy_headers,\n\u001b[32m    230\u001b[39m )\n\u001b[32m    232\u001b[39m \u001b[38;5;66;03m# botocore converts keys to str, so make sure that they are in\u001b[39;00m\n\u001b[32m    233\u001b[39m \u001b[38;5;66;03m# the expected case. See detailed discussion here:\u001b[39;00m\n\u001b[32m    234\u001b[39m \u001b[38;5;66;03m# https://github.com/aio-libs/aiobotocore/pull/116\u001b[39;00m\n\u001b[32m    235\u001b[39m \u001b[38;5;66;03m# aiohttp's CIMultiDict camel cases the headers :(\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiohttp/client.py:703\u001b[39m, in \u001b[36mClientSession._request\u001b[39m\u001b[34m(self, method, str_or_url, params, data, json, cookies, headers, skip_auto_headers, auth, allow_redirects, max_redirects, compress, chunked, expect100, raise_for_status, read_until_eof, proxy, proxy_auth, timeout, verify_ssl, fingerprint, ssl_context, ssl, server_hostname, proxy_headers, trace_request_ctx, read_bufsize, auto_decompress, max_line_size, max_field_size)\u001b[39m\n\u001b[32m    702\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m703\u001b[39m     conn = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._connector.connect(\n\u001b[32m    704\u001b[39m         req, traces=traces, timeout=real_timeout\n\u001b[32m    705\u001b[39m     )\n\u001b[32m    706\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m asyncio.TimeoutError \u001b[38;5;28;01mas\u001b[39;00m exc:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiohttp/connector.py:548\u001b[39m, in \u001b[36mBaseConnector.connect\u001b[39m\u001b[34m(self, req, traces, timeout)\u001b[39m\n\u001b[32m    547\u001b[39m         \u001b[38;5;28;01mawait\u001b[39;00m trace.send_connection_create_start()\n\u001b[32m--> \u001b[39m\u001b[32m548\u001b[39m proto = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._create_connection(req, traces, timeout)\n\u001b[32m    549\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m traces:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiohttp/connector.py:1056\u001b[39m, in \u001b[36mTCPConnector._create_connection\u001b[39m\u001b[34m(self, req, traces, timeout)\u001b[39m\n\u001b[32m   1055\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m-> \u001b[39m\u001b[32m1056\u001b[39m     _, proto = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._create_direct_connection(req, traces, timeout)\n\u001b[32m   1058\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m proto\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiohttp/connector.py:1357\u001b[39m, in \u001b[36mTCPConnector._create_direct_connection\u001b[39m\u001b[34m(self, req, traces, timeout, client_error)\u001b[39m\n\u001b[32m   1355\u001b[39m     \u001b[38;5;66;03m# in case of proxy it is not ClientProxyConnectionError\u001b[39;00m\n\u001b[32m   1356\u001b[39m     \u001b[38;5;66;03m# it is problem of resolving proxy ip itself\u001b[39;00m\n\u001b[32m-> \u001b[39m\u001b[32m1357\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m ClientConnectorDNSError(req.connection_key, exc) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mexc\u001b[39;00m\n\u001b[32m   1359\u001b[39m last_exc: Optional[\u001b[38;5;167;01mException\u001b[39;00m] = \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "\u001b[31mClientConnectorDNSError\u001b[39m: Cannot connect to host kafka-smp-bucket.s3.Ohious-east-2.amazonaws.com:443 ssl:default [nodename nor servname provided, or not known]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[31mEndpointConnectionError\u001b[39m                   Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[38]\u001b[39m\u001b[32m, line 2\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m count, i \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28menumerate\u001b[39m(consumer):\n\u001b[32m----> \u001b[39m\u001b[32m2\u001b[39m \u001b[43m   \u001b[49m\u001b[38;5;28;43;01mwith\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43ms3\u001b[49m\u001b[43m.\u001b[49m\u001b[43mopen\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43mf\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43ms3://kafka-smp-bucket/stock_market_\u001b[39;49m\u001b[38;5;132;43;01m{\u001b[39;49;00m\u001b[43mcount\u001b[49m\u001b[38;5;132;43;01m}\u001b[39;49;00m\u001b[33;43m.json\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[33;43m'\u001b[39;49m\u001b[33;43mw\u001b[39;49m\u001b[33;43m'\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mas\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mf\u001b[49m\u001b[43m:\u001b[49m\n\u001b[32m      3\u001b[39m \u001b[43m       \u001b[49m\u001b[43mjson\u001b[49m\u001b[43m.\u001b[49m\u001b[43mdump\u001b[49m\u001b[43m(\u001b[49m\u001b[43mi\u001b[49m\u001b[43m.\u001b[49m\u001b[43mvalue\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mf\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/fsspec/spec.py:2178\u001b[39m, in \u001b[36mAbstractBufferedFile.close\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m   2176\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m   2177\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m.forced:\n\u001b[32m-> \u001b[39m\u001b[32m2178\u001b[39m         \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mflush\u001b[49m\u001b[43m(\u001b[49m\u001b[43mforce\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n\u001b[32m   2180\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m.fs \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m   2181\u001b[39m         \u001b[38;5;28mself\u001b[39m.fs.invalidate_cache(\u001b[38;5;28mself\u001b[39m.path)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/fsspec/spec.py:2041\u001b[39m, in \u001b[36mAbstractBufferedFile.flush\u001b[39m\u001b[34m(self, force)\u001b[39m\n\u001b[32m   2038\u001b[39m         \u001b[38;5;28mself\u001b[39m.closed = \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[32m   2039\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m\n\u001b[32m-> \u001b[39m\u001b[32m2041\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_upload_chunk\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfinal\u001b[49m\u001b[43m=\u001b[49m\u001b[43mforce\u001b[49m\u001b[43m)\u001b[49m \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m:\n\u001b[32m   2042\u001b[39m     \u001b[38;5;28mself\u001b[39m.offset += \u001b[38;5;28mself\u001b[39m.buffer.seek(\u001b[32m0\u001b[39m, \u001b[32m2\u001b[39m)\n\u001b[32m   2043\u001b[39m     \u001b[38;5;28mself\u001b[39m.buffer = io.BytesIO()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/s3fs/core.py:2451\u001b[39m, in \u001b[36mS3File._upload_chunk\u001b[39m\u001b[34m(self, final)\u001b[39m\n\u001b[32m   2448\u001b[39m             upload_part(\u001b[38;5;28mself\u001b[39m.buffer.read(\u001b[38;5;28mself\u001b[39m.part_max))\n\u001b[32m   2450\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m.autocommit \u001b[38;5;129;01mand\u001b[39;00m final:\n\u001b[32m-> \u001b[39m\u001b[32m2451\u001b[39m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mcommit\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m   2452\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m   2453\u001b[39m     \u001b[38;5;66;03m# update 'upload offset'\u001b[39;00m\n\u001b[32m   2454\u001b[39m     \u001b[38;5;28mself\u001b[39m.offset += \u001b[38;5;28mself\u001b[39m.buffer.tell()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/s3fs/core.py:2476\u001b[39m, in \u001b[36mS3File.commit\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m   2474\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m.acl:\n\u001b[32m   2475\u001b[39m         kw[\u001b[33m\"\u001b[39m\u001b[33mACL\u001b[39m\u001b[33m\"\u001b[39m] = \u001b[38;5;28mself\u001b[39m.acl\n\u001b[32m-> \u001b[39m\u001b[32m2476\u001b[39m     write_result = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_call_s3\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mput_object\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkw\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m   2477\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m   2478\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/s3fs/core.py:2311\u001b[39m, in \u001b[36mS3File._call_s3\u001b[39m\u001b[34m(self, method, *kwarglist, **kwargs)\u001b[39m\n\u001b[32m   2310\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_call_s3\u001b[39m(\u001b[38;5;28mself\u001b[39m, method, *kwarglist, **kwargs):\n\u001b[32m-> \u001b[39m\u001b[32m2311\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mfs\u001b[49m\u001b[43m.\u001b[49m\u001b[43mcall_s3\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43ms3_additional_kwargs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwarglist\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/fsspec/asyn.py:118\u001b[39m, in \u001b[36msync_wrapper.<locals>.wrapper\u001b[39m\u001b[34m(*args, **kwargs)\u001b[39m\n\u001b[32m    115\u001b[39m \u001b[38;5;129m@functools\u001b[39m.wraps(func)\n\u001b[32m    116\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mwrapper\u001b[39m(*args, **kwargs):\n\u001b[32m    117\u001b[39m     \u001b[38;5;28mself\u001b[39m = obj \u001b[38;5;129;01mor\u001b[39;00m args[\u001b[32m0\u001b[39m]\n\u001b[32m--> \u001b[39m\u001b[32m118\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43msync\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mloop\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/fsspec/asyn.py:103\u001b[39m, in \u001b[36msync\u001b[39m\u001b[34m(loop, func, timeout, *args, **kwargs)\u001b[39m\n\u001b[32m    101\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m FSTimeoutError \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mreturn_result\u001b[39;00m\n\u001b[32m    102\u001b[39m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(return_result, \u001b[38;5;167;01mBaseException\u001b[39;00m):\n\u001b[32m--> \u001b[39m\u001b[32m103\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m return_result\n\u001b[32m    104\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    105\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m return_result\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/fsspec/asyn.py:56\u001b[39m, in \u001b[36m_runner\u001b[39m\u001b[34m(event, coro, result, timeout)\u001b[39m\n\u001b[32m     54\u001b[39m     coro = asyncio.wait_for(coro, timeout=timeout)\n\u001b[32m     55\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m---> \u001b[39m\u001b[32m56\u001b[39m     result[\u001b[32m0\u001b[39m] = \u001b[38;5;28;01mawait\u001b[39;00m coro\n\u001b[32m     57\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m ex:\n\u001b[32m     58\u001b[39m     result[\u001b[32m0\u001b[39m] = ex\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/s3fs/core.py:371\u001b[39m, in \u001b[36mS3FileSystem._call_s3\u001b[39m\u001b[34m(self, method, *akwarglist, **kwargs)\u001b[39m\n\u001b[32m    369\u001b[39m logger.debug(\u001b[33m\"\u001b[39m\u001b[33mCALL: \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m - \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m - \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m\"\u001b[39m, method.\u001b[34m__name__\u001b[39m, akwarglist, kw2)\n\u001b[32m    370\u001b[39m additional_kwargs = \u001b[38;5;28mself\u001b[39m._get_s3_method_kwargs(method, *akwarglist, **kwargs)\n\u001b[32m--> \u001b[39m\u001b[32m371\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m _error_wrapper(\n\u001b[32m    372\u001b[39m     method, kwargs=additional_kwargs, retries=\u001b[38;5;28mself\u001b[39m.retries\n\u001b[32m    373\u001b[39m )\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/s3fs/core.py:146\u001b[39m, in \u001b[36m_error_wrapper\u001b[39m\u001b[34m(func, args, kwargs, retries)\u001b[39m\n\u001b[32m    144\u001b[39m         err = e\n\u001b[32m    145\u001b[39m err = translate_boto_error(err)\n\u001b[32m--> \u001b[39m\u001b[32m146\u001b[39m \u001b[38;5;28;01mraise\u001b[39;00m err\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/s3fs/core.py:114\u001b[39m, in \u001b[36m_error_wrapper\u001b[39m\u001b[34m(func, args, kwargs, retries)\u001b[39m\n\u001b[32m    112\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m i \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(retries):\n\u001b[32m    113\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m114\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m func(*args, **kwargs)\n\u001b[32m    115\u001b[39m     \u001b[38;5;28;01mexcept\u001b[39;00m S3_RETRYABLE_ERRORS \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m    116\u001b[39m         err = e\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/client.py:394\u001b[39m, in \u001b[36mAioBaseClient._make_api_call\u001b[39m\u001b[34m(self, operation_name, api_params)\u001b[39m\n\u001b[32m    390\u001b[39m     maybe_compress_request(\n\u001b[32m    391\u001b[39m         \u001b[38;5;28mself\u001b[39m.meta.config, request_dict, operation_model\n\u001b[32m    392\u001b[39m     )\n\u001b[32m    393\u001b[39m     apply_request_checksum(request_dict)\n\u001b[32m--> \u001b[39m\u001b[32m394\u001b[39m     http, parsed_response = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._make_request(\n\u001b[32m    395\u001b[39m         operation_model, request_dict, request_context\n\u001b[32m    396\u001b[39m     )\n\u001b[32m    398\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m.meta.events.emit(\n\u001b[32m    399\u001b[39m     \u001b[33mf\u001b[39m\u001b[33m'\u001b[39m\u001b[33mafter-call.\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mservice_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m.\u001b[39m\u001b[38;5;132;01m{\u001b[39;00moperation_name\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m'\u001b[39m,\n\u001b[32m    400\u001b[39m     http_response=http,\n\u001b[32m   (...)\u001b[39m\u001b[32m    403\u001b[39m     context=request_context,\n\u001b[32m    404\u001b[39m )\n\u001b[32m    406\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m http.status_code >= \u001b[32m300\u001b[39m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/client.py:420\u001b[39m, in \u001b[36mAioBaseClient._make_request\u001b[39m\u001b[34m(self, operation_model, request_dict, request_context)\u001b[39m\n\u001b[32m    416\u001b[39m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_make_request\u001b[39m(\n\u001b[32m    417\u001b[39m     \u001b[38;5;28mself\u001b[39m, operation_model, request_dict, request_context\n\u001b[32m    418\u001b[39m ):\n\u001b[32m    419\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m420\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._endpoint.make_request(\n\u001b[32m    421\u001b[39m             operation_model, request_dict\n\u001b[32m    422\u001b[39m         )\n\u001b[32m    423\u001b[39m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m    424\u001b[39m         \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m.meta.events.emit(\n\u001b[32m    425\u001b[39m             \u001b[33mf\u001b[39m\u001b[33m'\u001b[39m\u001b[33mafter-call-error.\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m._service_model.service_id.hyphenize()\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m.\u001b[39m\u001b[38;5;132;01m{\u001b[39;00moperation_model.name\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m'\u001b[39m,\n\u001b[32m    426\u001b[39m             exception=e,\n\u001b[32m    427\u001b[39m             context=request_context,\n\u001b[32m    428\u001b[39m         )\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/endpoint.py:90\u001b[39m, in \u001b[36mAioEndpoint._send_request\u001b[39m\u001b[34m(self, request_dict, operation_model)\u001b[39m\n\u001b[32m     86\u001b[39m request = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m.create_request(request_dict, operation_model)\n\u001b[32m     87\u001b[39m success_response, exception = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._get_response(\n\u001b[32m     88\u001b[39m     request, operation_model, context\n\u001b[32m     89\u001b[39m )\n\u001b[32m---> \u001b[39m\u001b[32m90\u001b[39m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._needs_retry(\n\u001b[32m     91\u001b[39m     attempts,\n\u001b[32m     92\u001b[39m     operation_model,\n\u001b[32m     93\u001b[39m     request_dict,\n\u001b[32m     94\u001b[39m     success_response,\n\u001b[32m     95\u001b[39m     exception,\n\u001b[32m     96\u001b[39m ):\n\u001b[32m     97\u001b[39m     attempts += \u001b[32m1\u001b[39m\n\u001b[32m     98\u001b[39m     \u001b[38;5;28mself\u001b[39m._update_retries_context(context, attempts, success_response)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/endpoint.py:261\u001b[39m, in \u001b[36mAioEndpoint._needs_retry\u001b[39m\u001b[34m(self, attempts, operation_model, request_dict, response, caught_exception)\u001b[39m\n\u001b[32m    259\u001b[39m service_id = operation_model.service_model.service_id.hyphenize()\n\u001b[32m    260\u001b[39m event_name = \u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mneeds-retry.\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mservice_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m.\u001b[39m\u001b[38;5;132;01m{\u001b[39;00moperation_model.name\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m\n\u001b[32m--> \u001b[39m\u001b[32m261\u001b[39m responses = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._event_emitter.emit(\n\u001b[32m    262\u001b[39m     event_name,\n\u001b[32m    263\u001b[39m     response=response,\n\u001b[32m    264\u001b[39m     endpoint=\u001b[38;5;28mself\u001b[39m,\n\u001b[32m    265\u001b[39m     operation=operation_model,\n\u001b[32m    266\u001b[39m     attempts=attempts,\n\u001b[32m    267\u001b[39m     caught_exception=caught_exception,\n\u001b[32m    268\u001b[39m     request_dict=request_dict,\n\u001b[32m    269\u001b[39m )\n\u001b[32m    270\u001b[39m handler_response = first_non_none_response(responses)\n\u001b[32m    271\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m handler_response \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/hooks.py:68\u001b[39m, in \u001b[36mAioHierarchicalEmitter._emit\u001b[39m\u001b[34m(self, event_name, kwargs, stop_on_response)\u001b[39m\n\u001b[32m     65\u001b[39m logger.debug(\u001b[33m'\u001b[39m\u001b[33mEvent \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m: calling handler \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m'\u001b[39m, event_name, handler)\n\u001b[32m     67\u001b[39m \u001b[38;5;66;03m# Await the handler if its a coroutine.\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m68\u001b[39m response = \u001b[38;5;28;01mawait\u001b[39;00m resolve_awaitable(handler(**kwargs))\n\u001b[32m     69\u001b[39m responses.append((handler, response))\n\u001b[32m     70\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m stop_on_response \u001b[38;5;129;01mand\u001b[39;00m response \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/_helpers.py:6\u001b[39m, in \u001b[36mresolve_awaitable\u001b[39m\u001b[34m(obj)\u001b[39m\n\u001b[32m      4\u001b[39m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mresolve_awaitable\u001b[39m(obj):\n\u001b[32m      5\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m inspect.isawaitable(obj):\n\u001b[32m----> \u001b[39m\u001b[32m6\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m obj\n\u001b[32m      8\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m obj\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/retryhandler.py:107\u001b[39m, in \u001b[36mAioRetryHandler._call\u001b[39m\u001b[34m(self, attempts, response, caught_exception, **kwargs)\u001b[39m\n\u001b[32m    104\u001b[39m     retries_context = kwargs[\u001b[33m'\u001b[39m\u001b[33mrequest_dict\u001b[39m\u001b[33m'\u001b[39m][\u001b[33m'\u001b[39m\u001b[33mcontext\u001b[39m\u001b[33m'\u001b[39m].get(\u001b[33m'\u001b[39m\u001b[33mretries\u001b[39m\u001b[33m'\u001b[39m)\n\u001b[32m    105\u001b[39m     checker_kwargs.update({\u001b[33m'\u001b[39m\u001b[33mretries_context\u001b[39m\u001b[33m'\u001b[39m: retries_context})\n\u001b[32m--> \u001b[39m\u001b[32m107\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m resolve_awaitable(\u001b[38;5;28mself\u001b[39m._checker(**checker_kwargs)):\n\u001b[32m    108\u001b[39m     result = \u001b[38;5;28mself\u001b[39m._action(attempts=attempts)\n\u001b[32m    109\u001b[39m     logger.debug(\u001b[33m\"\u001b[39m\u001b[33mRetry needed, action of: \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[33m\"\u001b[39m, result)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/_helpers.py:6\u001b[39m, in \u001b[36mresolve_awaitable\u001b[39m\u001b[34m(obj)\u001b[39m\n\u001b[32m      4\u001b[39m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mresolve_awaitable\u001b[39m(obj):\n\u001b[32m      5\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m inspect.isawaitable(obj):\n\u001b[32m----> \u001b[39m\u001b[32m6\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m obj\n\u001b[32m      8\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m obj\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/retryhandler.py:126\u001b[39m, in \u001b[36mAioMaxAttemptsDecorator._call\u001b[39m\u001b[34m(self, attempt_number, response, caught_exception, retries_context)\u001b[39m\n\u001b[32m    121\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m retries_context:\n\u001b[32m    122\u001b[39m     retries_context[\u001b[33m'\u001b[39m\u001b[33mmax\u001b[39m\u001b[33m'\u001b[39m] = \u001b[38;5;28mmax\u001b[39m(\n\u001b[32m    123\u001b[39m         retries_context.get(\u001b[33m'\u001b[39m\u001b[33mmax\u001b[39m\u001b[33m'\u001b[39m, \u001b[32m0\u001b[39m), \u001b[38;5;28mself\u001b[39m._max_attempts\n\u001b[32m    124\u001b[39m     )\n\u001b[32m--> \u001b[39m\u001b[32m126\u001b[39m should_retry = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._should_retry(\n\u001b[32m    127\u001b[39m     attempt_number, response, caught_exception\n\u001b[32m    128\u001b[39m )\n\u001b[32m    129\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m should_retry:\n\u001b[32m    130\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m attempt_number >= \u001b[38;5;28mself\u001b[39m._max_attempts:\n\u001b[32m    131\u001b[39m         \u001b[38;5;66;03m# explicitly set MaxAttemptsReached\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/retryhandler.py:165\u001b[39m, in \u001b[36mAioMaxAttemptsDecorator._should_retry\u001b[39m\u001b[34m(self, attempt_number, response, caught_exception)\u001b[39m\n\u001b[32m    161\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[32m    162\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    163\u001b[39m     \u001b[38;5;66;03m# If we've exceeded the max attempts we just let the exception\u001b[39;00m\n\u001b[32m    164\u001b[39m     \u001b[38;5;66;03m# propagate if one has occurred.\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m165\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m resolve_awaitable(\n\u001b[32m    166\u001b[39m         \u001b[38;5;28mself\u001b[39m._checker(attempt_number, response, caught_exception)\n\u001b[32m    167\u001b[39m     )\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/_helpers.py:6\u001b[39m, in \u001b[36mresolve_awaitable\u001b[39m\u001b[34m(obj)\u001b[39m\n\u001b[32m      4\u001b[39m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mresolve_awaitable\u001b[39m(obj):\n\u001b[32m      5\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m inspect.isawaitable(obj):\n\u001b[32m----> \u001b[39m\u001b[32m6\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m obj\n\u001b[32m      8\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m obj\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/retryhandler.py:174\u001b[39m, in \u001b[36mAioMultiChecker._call\u001b[39m\u001b[34m(self, attempt_number, response, caught_exception)\u001b[39m\n\u001b[32m    171\u001b[39m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_call\u001b[39m(\u001b[38;5;28mself\u001b[39m, attempt_number, response, caught_exception):\n\u001b[32m    172\u001b[39m     \u001b[38;5;28;01mfor\u001b[39;00m checker \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m._checkers:\n\u001b[32m    173\u001b[39m         checker_response = \u001b[38;5;28;01mawait\u001b[39;00m resolve_awaitable(\n\u001b[32m--> \u001b[39m\u001b[32m174\u001b[39m             \u001b[43mchecker\u001b[49m\u001b[43m(\u001b[49m\u001b[43mattempt_number\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mresponse\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcaught_exception\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    175\u001b[39m         )\n\u001b[32m    176\u001b[39m         \u001b[38;5;28;01mif\u001b[39;00m checker_response:\n\u001b[32m    177\u001b[39m             \u001b[38;5;28;01mreturn\u001b[39;00m checker_response\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/botocore/retryhandler.py:247\u001b[39m, in \u001b[36mBaseChecker.__call__\u001b[39m\u001b[34m(self, attempt_number, response, caught_exception)\u001b[39m\n\u001b[32m    245\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m._check_response(attempt_number, response)\n\u001b[32m    246\u001b[39m \u001b[38;5;28;01melif\u001b[39;00m caught_exception \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m247\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_check_caught_exception\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    248\u001b[39m \u001b[43m        \u001b[49m\u001b[43mattempt_number\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcaught_exception\u001b[49m\n\u001b[32m    249\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    250\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    251\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[33m\"\u001b[39m\u001b[33mBoth response and caught_exception are None.\u001b[39m\u001b[33m\"\u001b[39m)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/botocore/retryhandler.py:416\u001b[39m, in \u001b[36mExceptionRaiser._check_caught_exception\u001b[39m\u001b[34m(self, attempt_number, caught_exception)\u001b[39m\n\u001b[32m    408\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_check_caught_exception\u001b[39m(\u001b[38;5;28mself\u001b[39m, attempt_number, caught_exception):\n\u001b[32m    409\u001b[39m     \u001b[38;5;66;03m# This is implementation specific, but this class is useful by\u001b[39;00m\n\u001b[32m    410\u001b[39m     \u001b[38;5;66;03m# coordinating with the MaxAttemptsDecorator.\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    414\u001b[39m     \u001b[38;5;66;03m# the MaxAttemptsDecorator is not interested in retrying the exception\u001b[39;00m\n\u001b[32m    415\u001b[39m     \u001b[38;5;66;03m# then this exception just propagates out past the retry code.\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m416\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m caught_exception\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/endpoint.py:171\u001b[39m, in \u001b[36mAioEndpoint._do_get_response\u001b[39m\u001b[34m(self, request, operation_model, context)\u001b[39m\n\u001b[32m    169\u001b[39m     http_response = first_non_none_response(responses)\n\u001b[32m    170\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m http_response \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m171\u001b[39m         http_response = \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m._send(request)\n\u001b[32m    172\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m HTTPClientError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m    173\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m (\u001b[38;5;28;01mNone\u001b[39;00m, e)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/endpoint.py:284\u001b[39m, in \u001b[36mAioEndpoint._send\u001b[39m\u001b[34m(self, request)\u001b[39m\n\u001b[32m    283\u001b[39m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_send\u001b[39m(\u001b[38;5;28mself\u001b[39m, request):\n\u001b[32m--> \u001b[39m\u001b[32m284\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m.http_session.send(request)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Downloads/Kafka_Stock_Market_Analysis/Kafka_Stock_Market_Analysis/path/to/venv/lib/python3.13/site-packages/aiobotocore/httpsession.py:276\u001b[39m, in \u001b[36mAIOHTTPSession.send\u001b[39m\u001b[34m(self, request)\u001b[39m\n\u001b[32m    270\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m ReadTimeoutError(endpoint_url=request.url, error=e)\n\u001b[32m    271\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m (\n\u001b[32m    272\u001b[39m     ClientConnectorError,\n\u001b[32m    273\u001b[39m     ClientConnectionError,\n\u001b[32m    274\u001b[39m     socket.gaierror,\n\u001b[32m    275\u001b[39m ) \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m--> \u001b[39m\u001b[32m276\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m EndpointConnectionError(endpoint_url=request.url, error=e)\n\u001b[32m    277\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m asyncio.TimeoutError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m    278\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m ReadTimeoutError(endpoint_url=request.url, error=e)\n",
      "\u001b[31mEndpointConnectionError\u001b[39m: Could not connect to the endpoint URL: \"https://kafka-smp-bucket.s3.Ohious-east-2.amazonaws.com/stock_market_0.json\""
     ]
    }
   ],
   "source": [
    "for count, i in enumerate(consumer):\n",
    "   with s3.open(f\"s3://kafka-smp-bucket/stock_market_{count}.json\", 'w') as f:\n",
    "       json.dump(i.value, f)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
